# ----------------------------------------------------------------------
# @ref: https://fly.io/docs/reference/configuration
# ----------------------------------------------------------------------

app = "CHANGEME_APP_NAME"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 256
console_command = "/bin/sh"

[build]
  # image = "ghcr.io/riipandi/trusty:latest"
  dockerfile = "Dockerfile"

[build.args]
  NODE_VERSION = "20"

[deploy]
  strategy = "immediate"
  # release_command = "/usr/local/bin/node dist/migrate.cjs migrate"

[env]
  BIND_ADDR = "0.0.0.0:8030"

[http_service]
  internal_port = 8030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.2", "TLSv1.3"]
    default_self_signed = false

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"
  protocol = "http"
  tls_skip_verify = true
